import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBarAndThemeWrapper from "./NavBarAndThemeWrapper";
import NavBarWithModals from "./NavBarWithModals";
import "./globals.css";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="luxury">
      <body className={inter.className}>
        <QueryClientProvider>
          <AuthProvider>
            <NavBarAndThemeWrapper>
              <NavBarWithModals />
              <Theme>{children}</Theme>
            </NavBarAndThemeWrapper>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
